version: '3.8'

services:
  api:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/nestjs
      - JWT_SECRET=your-super-secret-key
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  postgres:
    platform: linux/amd64
    image: postgres:13
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nestjs
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data: 